---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "user-v1-0-0-snapshot"
  labels:
    app: user
    appNameVersion: "user-v1-0-0-snapshot"
    "akka.lightbend.com/service-name": user
spec:
  replicas: 2
  selector:
    matchLabels:
      appNameVersion: "user-v1-0-0-snapshot"
  template:
    metadata:
      labels:
        app: user
        appNameVersion: "user-v1-0-0-snapshot"
        "akka.lightbend.com/service-name": user
    spec:
      restartPolicy: Always
      containers:
        - name: user
          image: "userimpl:1.0.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: "JAVA_OPTS"
              value: "-Dplay.server.pidfile.path=/dev/null -Dconfig.resource=rp-application.conf -Dplay.http.secret.key=659987c499b5c81688abff1dfffc21c6-be47183810f74972134ee87a1816b2f6 -Dplay.filters.hosts.allowed.0=192.168.99.100"
 
            - name: CASSANDRA_SERVICE_NAME
              value: "_cql._tcp.reactive-sandbox-cassandra.default.svc.cluster.local"
            - name: KAFKA_SERVICE_NAME
              value: "_broker._tcp.reactive-sandbox-kafka.default.svc.cluster.local"

          ports:
            - containerPort: 9000
              name: http
            - containerPort: 2552
              name: remoting
            - containerPort: 8558
              name: management
          volumeMounts: []
          command:
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            initialDelaySeconds: 60
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: user
  name: user
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
    - name: remoting
      port: 2552
      protocol: TCP
      targetPort: 2552
    - name: management
      port: 8558
      protocol: TCP
      targetPort: 8558
  selector:
    app: user
