---
apiVersion: "apps/v1beta2"
kind: Deployment
metadata:
  name: "webgateway-v1-0-0-snapshot"
  labels:
    app: webgateway
    appNameVersion: "webgateway-v1-0-0-snapshot"
    "akka.lightbend.com/service-name": webgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      appNameVersion: "webgateway-v1-0-0-snapshot"
  template:
    metadata:
      labels:
        app: webgateway
        appNameVersion: "webgateway-v1-0-0-snapshot"
        "akka.lightbend.com/service-name": webgateway
    spec:
      restartPolicy: Always
      containers:
        - name: webgateway
          image: "webgateway:1.0.0-SNAPSHOT"
          imagePullPolicy: IfNotPresent
          env:
            - name: "JAVA_OPTS"
              value: "-Dplay.http.secret.key=659987c499b5c81688abff1dfffc21c6-be47183810f74972134ee87a1816b2f6 -Dplay.filters.hosts.allowed.0=192.168.99.100"
            - name: "RP_APP_NAME"
              value: webGateway
            - name: "RP_APP_TYPE"
              value: lagom
            - name: "RP_APP_VERSION"
              value: "1.0.0-SNAPSHOT"
            - name: "RP_JAVA_OPTS"
              value: "-Dplay.server.pidfile.path=/dev/null -Dconfig.resource=rp-application.conf"
            - name: "RP_KUBERNETES_POD_IP"
              valueFrom:
                fieldRef:
                  fieldPath: "status.podIP"
            - name: "RP_KUBERNETES_POD_NAME"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.name"
            - name: "RP_MODULES"
              value: "common,service-discovery"
            - name: "RP_NAMESPACE"
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.namespace"
            - name: "RP_PLATFORM"
              value: kubernetes
          ports:
            - containerPort: 9000
              name: http
          volumeMounts: []
          command:
            - "/opt/docker/bin/rp-start"
          args:
            - "bin/webgateway"
      volumes: []
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webgateway
  name: webgateway
spec:
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: webgateway
